### ISSUE TITLE
The device closes prematurely when calling devRecoveryDevice

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet-js#110]
**Describe the bug**
When calling `devRecoveryDevice` to recover a seed, after entering the first word of the seed the console reports that it is not possible to send the word to the device because the it is closed and the operation fails.

**Environment information:**

- OS: Windows 10 and Ubuntu 18.4.1
- Platform: X64
- Firmware Version: 4164257

**Steps to Reproduce**

1) Connect a seedlees hardware wallet.
2) Open `/test/ test_codes.js` and change `const testRecovery = false;` to be `true`.
3) Run `node node test_codes.js` inside the `/test` folder.
4) Accept the operation in the hardware wallet and enter the requested word.

After following all the previous steps, the operation will be interrupted and you will end with an output similar to this one:

```
dev 80ee / 21 : usage_page:a8a8, usage:c0fc
dev 313a / 1 : usage_page:1890, usage:c298
Device Open
dev 80ee / 21 : usage_page:26d0, usage:c0f8
dev 313a / 1 : usage_page:1fb0, usage:c0f8
Writing a buffer of length  64 to the device
Received data of length:  64
That message says its size is:  2
msgid slice: Uint8Array [ 0, 26 ]
Slice: Uint8Array [ 0, 0, 0, 2 ]
Received header  msg this.kind:  MessageType_ButtonRequest  size:  2 buffer lenght:  64 
Remaining bytesToGet: -53
Device Close
Device Open
dev 80ee / 21 : usage_page:3030, usage:3030
dev 313a / 1 : usage_page:a8a8, usage:c0fc
Writing a buffer of length  64 to the device
Received data of length:  64
That message says its size is:  2
msgid slice: Uint8Array [ 0, 46 ]
Slice: Uint8Array [ 0, 0, 0, 2 ]
Received header  msg this.kind:  MessageType_WordRequest  size:  2 buffer lenght:  64 
Remaining bytesToGet: -53
Device Close
Button Loop operation completed
Device Open
dev 80ee / 21 : usage_page:1fb0, usage:c0f8
dev 313a / 1 : usage_page:0, usage:0
Going into WordAck loop
Device Close
Device Open
dev 80ee / 21 : usage_page:61, usage:0
dev 313a / 1 : usage_page:1fb0, usage:c0f8
Inside wordReader callback, please input word: 
wine
Device Close
(node:3911) UnhandledPromiseRejectionWarning: Error: Unable to read from a closed HID device
    at HID.read (/home/user/github/hardware-wallet-js/node_modules/node-hid/nodehid.js:95:11)
    at DeviceHandler.read (/home/user/github/hardware-wallet-js/device-wallet.js:184:17)
    at wordPromise.then (/home/user/github/hardware-wallet-js/device-wallet.js:987:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:3911) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3911) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Actual behavior**
After entering the fist word, the operation is interrupted with the `Unable to read from a closed HID device` error.

**Expected behavior**
The operation should continue. More words should be requested to the user and the seed should be recovered after entering all the words.

**Additional context**
The operation works correctly with the lastest version of the hardware wallet daemon and older versions of the JS library.

**Possible implementation**

**Comment by olemis** [comment]
>     3\. Run `node node test_codes.js` inside the `/test` folder.

At this step I am getting a different error 

```
$ node test_codes.js
Device Open
Device Open
Promise rejected Error: cannot open device with path IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS11@14600000/SKYWALLET@14600000/SKYCOIN Interface@0/IOUSBHostHIDDevice@14600000,0
    at new HID (/PATH/TO/skycoin/hardware-wallet-js/node_modules/node-hid/nodehid.js:54:17)
    at getDevice (/PATH/TO/skycoin/hardware-wallet-js/device-wallet.js:140:20)
    at DeviceHandler.getDeviceHandler (/PATH/TO/skycoin/hardware-wallet-js/device-wallet.js:220:19)
    at new DeviceHandler (/PATH/TO/skycoin/hardware-wallet-js/device-wallet.js:213:27)
    at devSendAddressGen (/PATH/TO/skycoin/hardware-wallet-js/device-wallet.js:755:28)
    at Promise (/PATH/TO/skycoin/hardware-wallet-js/device-wallet.js:844:5)
    at new Promise (<anonymous>)
    at Object.devAddressGen (/PATH/TO/skycoin/hardware-wallet-js/device-wallet.js:820:10)
    at Object.<anonymous> (/PATH/TO/skycoin/hardware-wallet-js/test/test_codes.js:99:32)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
Promise rejected Error: cannot open device with path IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS11@14600000/SKYWALLET@14600000/SKYCOIN Interface@0/IOUSBHostHIDDevice@14600000,0
    at new HID (/PATH/TO/skycoin/hardware-wallet-js/node_modules/node-hid/nodehid.js:54:17)
    at getDevice (/PATH/TO/skycoin/hardware-wallet-js/device-wallet.js:140:20)
    at DeviceHandler.getDeviceHandler (/PATH/TO/skycoin/hardware-wallet-js/device-wallet.js:220:19)
    at new DeviceHandler (/PATH/TO/skycoin/hardware-wallet-js/device-wallet.js:213:27)
    at Promise (/PATH/TO/skycoin/hardware-wallet-js/device-wallet.js:1090:26)
    at new Promise (<anonymous>)
    at Object.devRecoveryDevice (/PATH/TO/skycoin/hardware-wallet-js/device-wallet.js:1088:10)
    at Object.<anonymous> (/PATH/TO/skycoin/hardware-wallet-js/test/test_codes.js:135:32)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
```

**Comment by olemis** [comment]
The [HID issue](https://github.com/skycoin/hardware-wallet-js/issues/110#issuecomment-495801910) does not happen with hw-go library

**Comment by olemis** [comment]
@Senyoret1 there is something wrong with `test_codes.js` but I could not find what it is (... yet ...). The [issue I reported before](https://github.com/skycoin/hardware-wallet-js/issues/110#issuecomment-495801910) also happens if snippet for `devGetFeatures` is the only one enabled. Nonetheless it works if instructions run from `node` REPL .

```js
$ node
> dw = require('./device-wallet')
{ DeviceTypeEnum: { EMULATOR: 1, USB: 2 },
  devAddressGen: [Function: devAddressGen],
  devApplySettings: [Function: devApplySettings],
  devBackupDevice: [Function: devBackupDevice],
  devCancelRequest: [Function: devCancelRequest],
  devChangePin: [Function: devChangePin],
  devCheckMessageSignature: [Function: devCheckMessageSignature],
  devGenerateMnemonic: [Function: devGenerateMnemonic],
  devGetFeatures: [Function: devGetFeatures],
  devRecoveryDevice: [Function: devRecoveryDevice],
  devRemovePin: [Function: devRemovePin],
  devSetMnemonic: [Function: devSetMnemonic],
  devSkycoinSignMessage: [Function: devSkycoinSignMessage],
  devSkycoinTransactionSign: [Function: devSkycoinTransactionSign],
  devUpdateFirmware: [Function: devUpdateFirmware],
  devWipeDevice: [Function: devWipeDevice],
  getDevice: [Function: getDevice],
  makeSkywalletMessage: [Function: makeSkywalletMessage],
  setAutoPressButton: [Function: setAutoPressButton],
  setDeviceType: [Function: setDeviceType] }
> dw.set
dw.setAutoPressButton  dw.setDeviceType

> dw.setDeviceType(dw.DeviceTypeEnum.USB)
undefined
> dw.devRe
dw.devRecoveryDevice  dw.devRemovePin

> dw.devGetFeatures()
Device Open
Writing a buffer of length  64 to the device
Promise { <pending> }
> Received data of length:  64
That message says its size is:  111
msgid slice: Uint8Array [ 0, 17 ]
Slice: Uint8Array [ 0, 0, 0, 111 ]
Received header  msg this.kind:  MessageType_Features  size:  111 buffer lenght:  128
Remaining bytesToGet: 56
Reading one more time HID {
  _events: [Object: null prototype] { newListener: [Function] },
  _eventsCount: 1,
  _maxListeners: undefined,
  _raw: HID {},
  write: [Function: bound write],
  getFeatureReport: [Function: bound getFeatureReport],
  sendFeatureReport: [Function: bound sendFeatureReport],
  setNonBlocking: [Function: bound setNonBlocking],
  readSync: [Function: bound readSync],
  readTimeout: [Function: bound readTimeout],
  getDeviceInfo: [Function: bound getDeviceInfo],
  _paused: true }
Received data  msg kind:  MessageType_Features  size:  111 buffer lenght:  128
Remaining bytesToGet: -8
Device Close
Features message: vendor: Skycoin Foundation majorVersion: 0 minorVersion: 0 patchVersion: 0 bootloaderMode: false deviceId: 35383935065137331B003B00 pinProtection: false passphraseProtection: false language:  label:  initialized: false bootloaderHash: Uint8Array [
  176,
  116,
  162,
  71,
  92,
  25,
  181,
  200,
  192,
  109,
  12,
  66,
  210,
  204,
  118,
  222,
  11,
  154,
  16,
  92,
  202,
  210,
  48,
  15,
  50,
  204,
  235,
  97,
  198,
  198,
  245,
  104 ] pinCached: false passphraseCached: false firmwarePresent: false needsBackup: false model: 1 fwMajor: 1 fwMinor: 7 fwPatch: 0 fwVendor:  fwVendorKeys: <Buffer > unfinishedBackup: false
```

**Comment by olemis** [comment]
This is the actual error

```js
> dw.devRecoveryDevice(12, true, wordReader)
Device Open
Writing a buffer of length  64 to the device
Promise { <pending> }
> Received data of length:  64
That message says its size is:  2
msgid slice: Uint8Array [ 0, 26 ]
Slice: Uint8Array [ 0, 0, 0, 2 ]
Received header  msg this.kind:  MessageType_ButtonRequest  size:  2 buffer lenght:  64
Remaining bytesToGet: -53
Device Close
Device Open
Writing a buffer of length  64 to the device
Received data of length:  64
That message says its size is:  2
msgid slice: Uint8Array [ 0, 46 ]
Slice: Uint8Array [ 0, 0, 0, 2 ]
Received header  msg this.kind:  MessageType_WordRequest  size:  2 buffer lenght:  64
Remaining bytesToGet: -53
Device Close
Button Loop operation completed
Device Open
Going into WordAck loop
Device Close
Device Open
Inside wordReader callback, please input word:
Device Close
(node:39566) UnhandledPromiseRejectionWarning: ReferenceError: scanf is not defined
    at Promise (repl:4:20)
    at new Promise (<anonymous>)
    at wordReader (repl:2:12)
    at wordAckCallback (/PATH/TO/skycoin/hardware-wallet-js/device-wallet.js:1070:27)
    at wordAckLoop (/PATH/TO/skycoin/hardware-wallet-js/device-wallet.js:1083:3)
    at buttonAckLoop (/PATH/TO/skycoin/hardware-wallet-js/device-wallet.js:1097:11)
    at BufferReceiver.receiveBuffer (/PATH/TO/skycoin/hardware-wallet-js/buffer-receiver.js:50:7)
    at devHandleCallback (/PATH/TO/skycoin/hardware-wallet-js/device-wallet.js:245:24)
(node:39566) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:39566) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by olemis** [comment]
I finally could reproduce the issue after running this script

```js

scanf = require('scanf');
dw = require('./device-wallet')

dw.setDeviceType(dw.DeviceTypeEnum.USB);

const wordReader = function() {
  return new Promise((resolve) => {
    console.log("Inside wordReader callback, please input word: ");
    const word = scanf('%s');
    resolve(word);
  });
};

dw.devRecoveryDevice(12, true, wordReader);
```

Output :

```
Device Open
Writing a buffer of length  64 to the device
Received data of length:  64
That message says its size is:  2
msgid slice: Uint8Array [ 0, 26 ]
Slice: Uint8Array [ 0, 0, 0, 2 ]
Received header  msg this.kind:  MessageType_ButtonRequest  size:  2 buffer lenght:  64
Remaining bytesToGet: -53
Device Close
Device Open
Writing a buffer of length  64 to the device
Received data of length:  64
That message says its size is:  2
msgid slice: Uint8Array [ 0, 46 ]
Slice: Uint8Array [ 0, 0, 0, 2 ]
Received header  msg this.kind:  MessageType_WordRequest  size:  2 buffer lenght:  64
Remaining bytesToGet: -53
Device Close
Button Loop operation completed
Device Open
Going into WordAck loop
Device Close
Device Open
Inside wordReader callback, please input word:
suit
Device Close
(node:49649) UnhandledPromiseRejectionWarning: Error: Unable to read from a closed HID device
    at HID.read (/PATH/TO/skycoin/hardware-wallet-js/node_modules/node-hid/nodehid.js:95:11)
    at DeviceHandler.read (/PATH/TO/skycoin/hardware-wallet-js/device-wallet.js:251:17)
    at wordPromise.then (/PATH/TO/skycoin/hardware-wallet-js/device-wallet.js:1073:22)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:49649) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:49649) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

For the record, running `test_codes.js` does not work for me .

**Comment by olemis** [comment]
This is a weird issue . I could trace this back to 596f5989d8a753a0cbd8482201fd955e91203cbc as the version related to this issue since it works after checking out 4f8ffb1993404515185411aa5c511317fb7796bc . However the diff between them is only about whitespace.

**Comment by olemis** [comment]
it also works after checking out 4f8ffb1 parents i.e. 517c828f9d2bd82144c5bc91c58793256e387392 and 0778623d4bccaad6a3119fd262325c4b190abf4f
