### ISSUE TITLE
Error in pre-release test for check message signature

### ISSUE THREAD

**Issue by stdevStark** [skycoin/hardware-wallet-js#128]
**Describe the bug**
Pre-release steps for check sig fail

**Environment information:**

- OS: GNU/Linux
- Platform: Linux #1 SMP (Docker)
- Firmware Version: 1.7.0

**Steps to Reproduce**

At the point of test for check sig, save this code 

```js
dw = require("../skywallet");

dw.setDeviceType(dw.DeviceTypeEnum.USB);

const address = process.argv[2];
const message = process.argv[3];
const sig     = process.argv[4];

dw.devCheckMessageSignature(address, message, sig).
  then(console.log).
  catch(console.log);
```

... and run it like this

```sh
$ node code.js $ADDRESS1 $INPUT $SIG
```

... with values as results of pre-release test. Signature has to be returned by SkyWallet , rather than `skycoin-cli`

**Actual behavior**
This is the result

```
Device Open
Writing a buffer of length  256 to the device
Received data of length:  64
That message says its size is:  24
msgid slice: Uint8Array [ 0, 3 ]
Slice: Uint8Array [ 0, 0, 0, 24 ]
Received header  msg this.kind:  MessageType_Failure  size:  24 buffer lenght:  64
Remaining bytesToGet: -31
Device Close
Error: Wrong answer kind
    at devReadCallback (/go/linux/src/github.com/skycoin/hardware-wallet-js/skywallet.js:1024:16)
    at filterEntropyReqCallback (/go/linux/src/github.com/skycoin/hardware-wallet-js/skywallet.js:266:11)
    at BufferReceiver.receiveBuffer (/go/linux/src/github.com/skycoin/hardware-wallet-js/buffer-receiver.js:50:7)
    at devHandleCallback (/go/linux/src/github.com/skycoin/hardware-wallet-js/skywallet.js:282:24)

```

**Expected behavior**
Operation success

**Additional context**
Same happens if I change signature given by SkyWallet to use the one returned by `skycoin-cli`

**Comment by olemis** [comment]
> ```js
> dw.devCheckMessageSignature(address, message, sig).
> ```

I am not sure this is accurate ... @gz-c ?

**Comment by olemis** [comment]
>> ```js
>> dw.devCheckMessageSignature(address, message, sig).
>> ```
>> 
>> 
> 
> I am not sure this is accurate ... @gz-c ?
> 

indeed innerhash is used to sign transaction input , see [Transaction.SignInput()](https://github.com/skycoin/skycoin/blob/develop/src/coin/transactions.go#L304-L327).

**Comment by olemis** [comment]
> Error: Wrong answer kind
>     at devReadCallback (/go/linux/src/github.com/skycoin/hardware-wallet-js/skywallet.js:1024:16)
>     at filterEntropyReqCallback (/go/src/github.com/skycoin/hardware-wallet-js/skywallet.js:266:11)
>     at BufferReceiver.receiveBuffer (/go/src/github.com/skycoin/hardware-wallet-js/buffer-receiver.js:50:7)
>     at devHandleCallback (/go/src/github.com/skycoin/hardware-wallet-js/skywallet.js:282:24)

This has to be fixed though by parsing failure message correctly .

BTW @stdevStark what d'u see in device screen after this ?

**Comment by olemis** [comment]
this could be an issue in firmware not requesting user confirmation to sign message .
